import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const chakra_petch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`max-w-[1440px] w-full h-full mx-auto ${chakra_petch.className}`}
      >
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
